### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by srwareham**
Update readme to clarify that server does not need to have an internet-accessible IP address

### CODE REVIEW

**Comment by srwareham** [comment]
Simple documentation PR. The setup instructions worked great. When doing so, my reading of the docs made it seem like the server IP had to be internet accessible (by Spotify's servers). I tried setting up with a LAN IP and everything went great. Just added some minor tweaks to help future newbies.

**Comment by glensc** [comment]
@Yooooomi: LGTM

**Comment by Yooooomi** [comment]
Taken into account, will be available next release. Thanks!

**Comment by glensc** [comment]
please share commits as well that implemented these changes

**Pull request closed without merging**
