### PR TITLE
Reverse proxy improvements and docker compose organization

### PR DESCRIPTION
**Pull request by parbhatia**
This is how I set this project for personal use.
I wouldn't mind if you ignored this PR.

- added nginx reverse proxy (port 80) in front of frontend and backend (you're able to handle cors solely in nginx instead of doing it in the node server)
- you run the app on `localhost` now instead of `localhost:3000`
- added nginx for static react build in production (pretty sure it'll be faster than the serve package)
- reduced docker production builds by a bit
- added docker compose template layers which follow dev,stage,prod pattern
- inject env variables consistently using seperate layered env files
- reduced some env variables
- reduced spotify redirect url to only  `http://localhost/api/oauth/spotify/callback` 

`./dev.sh` to run dev environment
`./stage.sh` to run staging (this will build images you'd push to a resgistry)

### CODE REVIEW

**Comment by Yooooomi** [comment]
Hello! Thanks for your pr and your vision of how to setup this app.
There are few things you deleted/created that breaks the scalability of the app.

- API_ENDPOINT in the web is hardcoded to localhost, meaning you cannot access the tool from anywhere outside the device running it.
- MONGO_ENDPOINT is removed, which means you cannot connect to another mongo or if this mongo container name is not exactly mongo
- I don't know how your production Dockerfile works without having devDependencies during build, it's a miracle but shouldn't work, or at least it's not the way to do this
- Nginx is good but I feel like (as explained [here](https://github.com/Yooooomi/your_spotify/issues/77#issuecomment-1046010530)) this is not needed in the core YourSpotify project.

However there are few good points that I think I will implement concerning the cleaning of Dockerfiles concerning paths.

**Comment by parbhatia** [comment]
Valid points. The idea was someone could modify the nginx file (to add their own domain and certificates if they liked), so you could still use localhost to communicate between the frontend and backend. Mongo endpoint removal was something i did since i use unique service names anyways, but i can see how providing more parameters can be flexible.

If by production you mean staging, I think i'm still installing dev dependencies when i run yarn install for the server production file (i had never used yarn), or with the `--production=false` for the client.

I read your points on not using a reverse proxy, but you mentioned good reasons. Though I still strongly think you should use nginx to serve the static frontend, instead of relying on `serve`. If error handling in a concern, it'll be one nginx block you can add for wildcard matches.

I'm glad you found something useful. It's been a while since I did any docker compose work, but seeing your docker compose setup made me start tinkering. With docker compose, it's a always a little difficult to create modularized components that can share environements, but still remain flexible on their own.

**Comment by parbhatia** [comment]
I'm curious to hear why you opted to having the spotify client id and secret as environment variables, rather than allowing users to input them through the frontend, and storing them in the database.

**Comment by Yooooomi** [comment]
I don't know I began that way and never thought to change. But since this is a one time setup I don't see why one would change it in realtime. Client and secret are a bit like endpoints, if it's wrong it doesn't work and there's only one value that is meant to be here.

**Pull request closed without merging**
