### PR TITLE
Perf improvements

### PR DESCRIPTION
**Pull request by Yooooomi**

### CODE REVIEW

**Comment by Yooooomi** [comment]
@quentinguidee If you're good with that we can merge to master, and possibly release 1.8.0 tomorrow (in 12 hours in my country).

**Comment by quentinguidee** [comment]
The /gethistory seems still pretty slow for no reasons? Or am I missing something?

Other than that I thunk it's ready for 1.8.0!

**Comment by Yooooomi** [comment]
It's really not that slow for me, or what do you mean by slow?

**Comment by quentinguidee** [comment]
I mean it takes more than 1 second for only some last tracks, that seems slow compared to other requests that perform more complex computations

**Comment by Yooooomi** [comment]
So weird to be able to spam click the ranks on the artist page. Every page loads nearly instantaneously. I just spent 15 minutes exploring my stats. Thanks a lot for the work and the motivation you gave me to improve the project.

**Comment by Karakazz** [comment]
> So weird to be able to spam click the ranks on the artist page. Every page loads nearly instantaneously. I just spent 15 minutes exploring my stats. Thanks a lot for the work and the motivation you gave me to improve the project.

The feel of the app is entirely different! It feels really nice to click on 'All' and get your entire stats in a few seconds compared to waiting 30-60 seconds. 
| GET /spotify/songs_per?start=2019-01-12T15:09:23.000Z&end=2024-03-03T01:35:31.624Z&timeSplit=all 304 **2267.107 ms** - -
120110 songs listened

Great work!

**Pull request merged**
