### PR TITLE
Add release Github workflows to push Docker build and push images with version's tag

### LINKED ISSUE #210: [Feature Request] Build and publish docker images with proper tags
**Describe the issue**

Currently, docker images are only available with the "latest" tag, this can create unforseen issues during basic maintenance operation and it doesn't allow for fine version control.

**Expected behavior**

All docker images should be tagged using the app version

### PR DESCRIPTION
**Pull request by Byh0ki**
This PR aims to close #210

### CODE REVIEW

**Comment by Byh0ki** [comment]
Hello,

Yes that's the idea, like that it is easy to test a new change either on the client or the server and when a new release is published, a docker image with the corresponding tag is available

This is my first time working with Github action, hopefully everything works on the first try :sweat_smile:

**Comment by Yooooomi** [comment]
Do you feel like "nightly" updates should be tagged as latest? I feel like only releases should be tagged with latest, so that people don't pull non release updates.

**Comment by Byh0ki** [comment]
Indeed, we could add a `nightly` tag!

Do you think we still need to have the 2 steps, one for the client and one for the server or could we build new images at each commit for both?

**Comment by Yooooomi** [comment]
This is something that has already been discussed in #77. I feel like the migration for users from 2 to one container is painful. Also, having 1 container requires a bit more setup in the containers.

**Comment by Byh0ki** [comment]
I'm not talking about merging the 2 images in one but only building both of the containers at each commit instead of having rules to only build one or the other depending on the modified code

**Comment by Yooooomi** [comment]
Makes sense since if one builds and the other fails, the latest server is not compatible with the client.

**Comment by Byh0ki** [comment]
I've updated my PR, let me know if the new version is ok for you

**Comment by Yooooomi** [comment]
It seems good to me! Nice job :)

**Pull request merged**
