### PR TITLE
Add meta description and image

### PR DESCRIPTION
**Pull request by michaelkennethdavid**
Added meta description and image that will be used as a preview when the link to the app is shared.

Slack
image

Discord
image

### CODE REVIEW

**Comment by Yooooomi** [comment]
I'm wondering if we could fetch the image directly from the backend, thus not having to add the env variable.

**Comment by Yooooomi** [comment]
Made few changes to your PR, feel free to review them. I'll merge this this evening with the new release

**Comment by michaelkennethdavid** [comment]
I noticed that you remove the `index.html`. Running the `./build.sh` with in clean state (without `index.html`) will result in an error.

```
 => ERROR [builder 15/15] RUN sh scripts/build/*.sh                                                                  1.7s
------
 > [builder 15/15] RUN sh scripts/build/*.sh:
#20 0.401 NODE_ENV is 'production'
#20 0.504 yarn run v1.22.19
#20 0.524 $ react-scripts build
#20 1.573 Could not find a required file.
#20 1.573   Name: index.html
#20 1.573   Searched in: /app/public
#20 1.587 error Command failed with exit code 1.
#20 1.587 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by Yooooomi** [comment]
Oh damn, my bad, need to find a way to edit the index.html before running, will take a look in a few hours

**Comment by michaelkennethdavid** [comment]
* Add sed command to update the meta image URL to the current API_ENDPOINT value
* Add index.html back since yarn won't build without it.
* Cannot find the static image after building the docker image so I added command to copy it.

**Comment by Yooooomi** [comment]
Thanks for the work you put into and the screenshot, great work. Thanks again

**Pull request merged**
